# Generated by Django 4.2.9 on 2026-03-27 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('coins_scraped', models.IntegerField(default=0)),
                ('coins_failed', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('above', 'Price goes above'), ('below', 'Price goes below')], max_length=10)),
                ('target_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.coin')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('market_cap_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('volume_24h_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('change_24h_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('change_7d_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('scraped_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='dashboard.coin')),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['coin', 'scraped_at'], name='dashboard_p_coin_id_f1d681_idx')],
            },
        ),
    ]
